### ISSUE TITLE
Need help understanding Java

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox-engine-java#5]
[Nanobox Desktop](https://desktop.nanobox.io) automates the creation of isolated, virtual development environments. It scans your code and builds a suitable environment within a VM. In order to best automate the build of Java environments, we would greatly appreciate it if you would be willing to answer some or all of the following questions, in as much detail as you can. There are no wrong answers:
### Detection
- What is the most accurate way you can think of to detect a Java app?
### Environment
- Which java runtimes need to be available to your app?
- Are any other runtimes (nodejs, python, etc) needed?
- Are any utilities, webservers, or other binaries (apache, nginx, etc) needed?
- How do you manage/install dependencies?
- Where are your dependencies stored? (which directories)
### Service detection
- Does your app depend on services like postgres, redis, etc?
- How could we detect that your app depends on them?
- Does your app require any special configuration for these services?
### Application configuration
- Does your app require special configuration via config files or environment variables?
- Where and how could we configure your app to connect to the services that were previously detected?
### Compilation/Build
- Does your app need to be compiled?
- Is there a build process required to generate a release?
- Ultimately, what should be copied into the live environment? (all source code, specific directories, etc)
### Finally, running your app
- Is your app strictly a web (http) app, or does it provide a service on tcp/udp as well?
- How do you run your app?

Thanks in advance for sharing your time and expertise!

**Comment by Andrew-College** [comment]
Thank you very much for this project.
It's a really neat idea that'll (hopefully) make deploying java apps easier!

To explain myself. I'm a coder of the Javas and a few other languages, my second-last job and College project were forged in its enclosures. I've done Big Data(-ish) and Image Processing(-kinda) projects, Android Development as well as Windows Development, as well as a few fun little off and online pet-projects. While I may not be the typical use-case, I hope some of my two-cents will be useful to helping you figure out some handy stuff to put in the Java Engine.

If it's ok, I'd like to describe more the things that I have come across over a few separate projects, rather than focus on one particular/ current so my answers are really geared towards that end of things.

> **Detection**
> To my mind, a build manager shouldn't be assumed. Smaller projects/ starter projects might not even have these files. It would be most intuitive to go hunting for *.java (source files), *.javac (compiled source files), *.jar (Bundled Archives, that may be executable). 
> 
> **Environment**
> Java Version 9 ( 8?) is(, at time of remembering) the latest version of Java out there. As such, I have yet to run into a legacy requirement throughout the smattering of work I have done in the Java Code Mines!  :hammer: 
> If you were to tune the Engine for _just_ running java stuff, then maybe you could get away with just Installing the JRE. Most any compiled JAR should hold the necessary libraries to keep it happy, so a lot of the rest of what I have below would be moot.
> 
> > **Runtimes**
> > I've only really come across 'solutions' that 'add' more 'work to manage the solution'. Really Java does the do, with just it, it, and itself. That said, as a kindof nice overall Framework/ Build Manager/ Web Thingie, the [Play! Framework](https://www.playframework.com/) does a pretty solid job (Scala & Java, 'cuz why not?)
> > 
> > **Utilities**
> > Really alot of stuff is handled by the Build Manager(s). at most, when I had to deploy .war's, I'd need something like [Jetty](http://www.eclipse.org/jetty/) to locally double check my work (The Play Framework also has some sort of web service, but I'll let you discover that fun ;)).
> > With Regards to Version Control Software; Git, and SubVersion have been my main means of making my 'masterpieces' available. And as regards IDE's
> > 
> > **Dependency Management**
> > Here's where most of the [F.U.N &#8482; ](http://dwarffortresswiki.org/index.php/DF2014:Losing) happens. To date, I am aware of/ have used:
> > - [x] Maven
> > - [x] Ant
> > - [ ] Ivy
> > - [x] SBT
> > - [x] Gradle
> > - [ ] Leningen
> >   All of these utilities would be somewhat necessary because depending on what you're doing (i.e. Google Android / Web Toolkit Development) you're gonna need a [few](http://www.gwtproject.org/) [ancillary](https://developer.android.com/sdk/index.html) [things](http://stackoverflow.com/).
> 
> **Services/ Service Detection**
> When I was working on starting the Big Data projects, alot of time was spent in Apache Projects and tackling WSO2. I couldn't say I am a great authority, but In general, I'd say a good few of the Apache tools would be handy in the Java Engine. The examples I'd give would be:
> *[h2 (Pretty powerfull lil' (non-apache) bugger)](http://www.h2database.com/html/main.html)
> *[Cassandra (For what h2 don't wanna do)](http://cassandra.apache.org/)
> *[Derby](http://db.apache.org/derby/)
> These are all really databases of differing spec. We'd used h2 for keeping an accesible config rollout of our projects, with Cassandra and Solr holding up the ungodly outflow from Flume (boy, there are a few of these aren't there...).
> 
> > Detection
> > Detecting these is really down to two camps:
> > 1. Port Scan: each one of these Apache Jobs try to borrow some of the local (I'm assuming local for handiness sake) port space with defaults. 
> > 2. Goin' a-file huntin': I can't remember exactly where the config files are buried, but the Apache Docs are pretty solid for getting you where you need to go.
> 
> Environment II: The path to enlightenment
> As a whole, I've never really needed to worry about Environment Variables. NOt useful for this, but alot of the time, I'd use the Windows Registry to hold the few flags I needed to persist between Users, etc.
> 
> Compilation
> As I'd like to do development/tweaking in a nano box, I'd like to be able to run muh Build and Dependency Managers (such as Maven et al. above). 
> Generally, builds are a cycle of **mvn clean package** => **Fail** => **Swear** => **mvn clean-all** => **mvn package** => **Pass** => **Celebrate the Second Coming** => **copy WAR to folder** => **Jetty Fails, but doesn't crash** => **Go home a happy miner:godmode:**
> 
> Running
> Java stuff is easy enough to start up:
> 
> ``` Bash
> java -cp class.class.<many classes later>.mainClass program.jar
> ```
> 
> With the Play! Framework it's:
> 
> ``` Bash
> activator dev/ run
> ```

Hopefully this will all be of some use. Any question I will try to answer as best I can.

Regards,
Sans (not that one)
