### ISSUE TITLE
libjili.so appears to be missing

### ISSUE THREAD

**Issue by Andrew-College** [nanobox-io/nanobox-engine-java#9]
Hi there,

I've been trying out the Java Engine, and I have noticed that I cannot run the JVM because of a missing library.
I haven't done any modifications, so I believe this is on a standard build of the Java Engine?

![image](https://cloud.githubusercontent.com/assets/2452569/11353704/6a8630dc-923d-11e5-934d-42c8adca3c30.png)

Regards,
Andrew

**Comment by glinton** [comment]
Thanks for submitting this, I'll make sure the package maintainer has a look at the package, in the meantime, you can use `sun-jdk8` as your 'runtime' to work around this error.  
Boxfile

```
build:
  java_runtime: 'sun-jdk8'
```
